// ============================================================================
// lib/lab-templates.ts
// قوالب التحاليل الطبية الجاهزة للطباعة مع القيم المرجعية وطريقة الحساب
// تم ضبط كافة الحقول والمصطلحات باللغة الإنجليزية الطبية المعتمدة للتقارير
// ============================================================================

export interface LabTestField {
  id: string;
  nameAr: string;
  nameEn: string;
  unit: string;
  defaultValue?: string | number;
  normalRange: string; // Pure English reference range for reports
  section?: 'physical' | 'chemical' | 'microscopic'; // For structured reports like Urinalysis
  normalMin?: number;
  normalMax?: number;
  options?: string[];
}

export interface LabTemplate {
  id: string;
  titleAr: string;
  titleEn: string;
  category: string;
  categoryEn: string;
  methodology?: string;
  notesDefault?: string;
  notesDefaultEn?: string;
  isStructuredSections?: boolean; // For Urinalysis 2-column or structured view
  fields: LabTestField[];
  interpret?: (values: Record<string, string | number>) => {
    status: 'normal' | 'borderline' | 'abnormal' | 'high' | 'low';
    summaryAr: string;
    detailsAr: string;
  };
}

export const LAB_TEMPLATES: LabTemplate[] = [
  {
    id: 'hba1c',
    titleAr: 'تحليل السكر التراكمي',
    titleEn: 'Glycosylated Hemoglobin (HbA1c)',
    category: 'السكري والميتابوليزم',
    categoryEn: 'Diabetes & Metabolism',
    methodology: 'HPLC / Enzymatic Turbidimetric (NGSP & IFCC Standardized)',
    notesDefault: 'يُنصح بإعادة فحص السكر التراكمي كل 3 أشهر لمتابعة فاعلية الخطة العلاجية وضبط الجرعات بالتنسيق مع الطبيب المعالج.',
    notesDefaultEn: 'HbA1c reflects average blood glucose over the past 8 to 12 weeks. Routine 3-month re-testing is recommended for diabetic management in coordination with the physician.',
    fields: [
      {
        id: 'hba1c_val',
        nameAr: 'نسبة السكر التراكمي (HbA1c)',
        nameEn: 'Glycosylated Hemoglobin (HbA1c)',
        unit: '%',
        defaultValue: '6.5',
        normalRange: '< 5.7 % (Non-diabetic)',
        normalMin: 4.0,
        normalMax: 5.6,
      },
      {
        id: 'eag_val',
        nameAr: 'متوسط الجلوكوز التقديري (eAG)',
        nameEn: 'Estimated Average Glucose (eAG)',
        unit: 'mg/dL',
        defaultValue: '140',
        normalRange: '70 - 114 mg/dL',
        normalMin: 70,
        normalMax: 114,
      },
    ],
    interpret: (vals) => {
      const val = Number(vals['hba1c_val'] || 0);
      if (val < 4.0) {
        return {
          status: 'low',
          summaryAr: 'انخفاض في نسبة السكر التراكمي (< 4.0%)',
          detailsAr: 'قد يشير إلى هبوط متكرر في السكر أو أمراض دم أو أنيميا انحلالية، يُرجى استشارة الطبيب.',
        };
      }
      if (val <= 5.6) {
        return {
          status: 'normal',
          summaryAr: 'المعدل الطبيعي للأصحاء (4.0 - 5.6%)',
          detailsAr: 'المستوى طبيعي ولا توجد مؤشرات إصابة بداء السكري، يُنصح بالمحافظة على نمط الحياة الصحي.',
        };
      }
      if (val <= 6.4) {
        return {
          status: 'borderline',
          summaryAr: 'مرحلة ما قبل السكري - Prediabetes (5.7 - 6.4%)',
          detailsAr: 'ارتفاع في خطورة الإصابة بالسكري، يُوصى بتعديل النظام الغذائي وممارسة الرياضة والمتابعة الدورية.',
        };
      }
      if (val <= 7.0) {
        return {
          status: 'normal',
          summaryAr: 'سكري متحكم به ممتاز - Good Control (6.5 - 7.0%)',
          detailsAr: 'النتيجة تحقق الهدف العلاجي لمرضى السكري وفق توصيات الجمعية الأمريكية للسكري (ADA < 7.0%).',
        };
      }
      if (val <= 8.0) {
        return {
          status: 'borderline',
          summaryAr: 'سكري - تحكم متوسط مقبول (7.1 - 8.0%)',
          detailsAr: 'تحكم مقبول ولكن يحتاج إلى مزيد من الالتزام بالحمية الغذائية ومراجعة جرعات العلاج مع الطبيب.',
        };
      }
      return {
        status: 'high',
        summaryAr: 'سكري غير منضبط - Action Suggested (> 8.0%)',
        detailsAr: 'مستوى مرتفع يشير إلى ضعف التحكم في مستويات السكر وزيادة احتمالية المضاعفات. يتطلب مراجعة الطبيب الفورية لتعديل الخطة العلاجية.',
      };
    },
  },
  {
    id: 'glucose_fasting_random',
    titleAr: 'سكر الدم (صائم وعشوائي)',
    titleEn: 'Blood Glucose Profile (FBS / RBS)',
    category: 'السكري والميتابوليزم',
    categoryEn: 'Diabetes & Metabolism',
    methodology: 'Hexokinase / Glucose Oxidase Method',
    notesDefault: 'تم سحب العينة في شروط الصيام المحددة (8 - 10 ساعات للصائم).',
    notesDefaultEn: 'Specimen collected under standard fasting/random protocols. Clinical correlation with HbA1c is advised.',
    fields: [
      {
        id: 'fbs',
        nameAr: 'السكر الصائم (FBS)',
        nameEn: 'Fasting Blood Sugar (FBS)',
        unit: 'mg/dL',
        defaultValue: '95',
        normalRange: '70 - 100 mg/dL',
        normalMin: 70,
        normalMax: 100,
      },
      {
        id: 'rbs',
        nameAr: 'السكر العشوائي (RBS)',
        nameEn: 'Random Blood Sugar (RBS)',
        unit: 'mg/dL',
        defaultValue: '120',
        normalRange: '70 - 140 mg/dL',
        normalMin: 70,
        normalMax: 140,
      },
      {
        id: 'ppbs',
        nameAr: 'السكر بعد الأكل بساعتين (2h PPBS)',
        nameEn: '2-Hour Postprandial Glucose (2h PPBS)',
        unit: 'mg/dL',
        defaultValue: '130',
        normalRange: '< 140 mg/dL',
        normalMin: 70,
        normalMax: 140,
      },
    ],
  },
  {
    id: 'urinalysis',
    titleAr: 'تحليل البول الكامل',
    titleEn: 'Complete Urine Analysis',
    category: 'التحاليل المجهرية',
    categoryEn: 'Clinical Microscopy & Urinalysis',
    methodology: 'Automated Reflectance Photometry & High Power Microscopic Field (HPF)',
    isStructuredSections: true,
    notesDefault: 'فحص مجهري وفيزيائي وكيميائي شامل.',
    notesDefaultEn: 'Fresh midstream clean-catch urine specimen. Analyzed by automated strip photometry and microscopic sediment examination.',
    fields: [
      // Physical Examination
      {
        id: 'color',
        section: 'physical',
        nameAr: 'اللون (Color)',
        nameEn: 'Color',
        unit: '',
        defaultValue: 'Pale Yellow',
        normalRange: 'Pale Yellow - Amber',
      },
      {
        id: 'aspect',
        section: 'physical',
        nameAr: 'المظهر والشفافية (Aspect / Clarity)',
        nameEn: 'Aspect / Clarity',
        unit: '',
        defaultValue: 'Clear',
        normalRange: 'Clear',
      },
      {
        id: 'sp_gravity',
        section: 'physical',
        nameAr: 'الكثافة النوعية (Specific Gravity)',
        nameEn: 'Specific Gravity',
        unit: '',
        defaultValue: '1.020',
        normalRange: '1.010 - 1.025',
      },
      {
        id: 'ph',
        section: 'physical',
        nameAr: 'درجة الحموضة (pH)',
        nameEn: 'pH Reaction',
        unit: '',
        defaultValue: '6.0',
        normalRange: '5.0 - 7.5 (Acidic)',
      },

      // Chemical Examination
      {
        id: 'protein',
        section: 'chemical',
        nameAr: 'الزلال / البروتين (Protein)',
        nameEn: 'Protein (Albumin)',
        unit: '',
        defaultValue: 'Negative (Nil)',
        normalRange: 'Negative',
      },
      {
        id: 'glucose',
        section: 'chemical',
        nameAr: 'السكر في البول (Glucose)',
        nameEn: 'Glucose (Sugar)',
        unit: '',
        defaultValue: 'Negative (Nil)',
        normalRange: 'Negative',
      },
      {
        id: 'ketones',
        section: 'chemical',
        nameAr: 'الأجسام الكيتونية (Ketones)',
        nameEn: 'Ketone Bodies',
        unit: '',
        defaultValue: 'Negative',
        normalRange: 'Negative',
      },
      {
        id: 'nitrite',
        section: 'chemical',
        nameAr: 'النيتريت (Nitrite)',
        nameEn: 'Nitrite',
        unit: '',
        defaultValue: 'Negative',
        normalRange: 'Negative',
      },
      {
        id: 'bilirubin',
        section: 'chemical',
        nameAr: 'البيليروبين (Bilirubin)',
        nameEn: 'Bilirubin',
        unit: '',
        defaultValue: 'Negative',
        normalRange: 'Negative',
      },
      {
        id: 'urobilinogen',
        section: 'chemical',
        nameAr: 'اليوروبيلينوجين (Urobilinogen)',
        nameEn: 'Urobilinogen',
        unit: '',
        defaultValue: 'Normal',
        normalRange: 'Normal (< 1.0 mg/dL)',
      },

      // Microscopic Examination
      {
        id: 'pus_cells',
        section: 'microscopic',
        nameAr: 'خلايا الصديد (Pus Cells / WBCs)',
        nameEn: 'Pus Cells (WBCs)',
        unit: '/ HPF',
        defaultValue: '2 - 4',
        normalRange: '0 - 5 / HPF',
      },
      {
        id: 'rbcs',
        section: 'microscopic',
        nameAr: 'كرات الدم الحمراء (R.B.Cs)',
        nameEn: 'Red Blood Cells (RBCs)',
        unit: '/ HPF',
        defaultValue: '1 - 2',
        normalRange: '0 - 3 / HPF',
      },
      {
        id: 'epithelial_cells',
        section: 'microscopic',
        nameAr: 'الخلايا الظهارية (Epithelial Cells)',
        nameEn: 'Epithelial Cells',
        unit: '/ HPF',
        defaultValue: 'Few',
        normalRange: 'Nil - Few / HPF',
      },
      {
        id: 'crystals',
        section: 'microscopic',
        nameAr: 'الأملاح والبلورات (Crystals)',
        nameEn: 'Crystals',
        unit: '',
        defaultValue: 'Few Uric Acid Crystals',
        normalRange: 'Nil / Occasional',
      },
      {
        id: 'casts',
        section: 'microscopic',
        nameAr: 'الاسطوانات (Casts)',
        nameEn: 'Casts',
        unit: '/ HPF',
        defaultValue: 'Nil',
        normalRange: 'Negative / HPF',
      },
      {
        id: 'bacteria',
        section: 'microscopic',
        nameAr: 'البكتيريا (Bacteria)',
        nameEn: 'Bacteria',
        unit: '',
        defaultValue: 'Nil',
        normalRange: 'Negative',
      },
      {
        id: 'mucus',
        section: 'microscopic',
        nameAr: 'خيوط المخاط (Mucus)',
        nameEn: 'Mucus Threads',
        unit: '',
        defaultValue: 'Nil',
        normalRange: 'Negative',
      },
    ],
  },
  {
    id: 'cbc',
    titleAr: 'صورة الدم الكاملة',
    titleEn: 'Complete Blood Count (C.B.C)',
    category: 'أمراض الدم',
    categoryEn: 'Hematology',
    methodology: 'Automated 5-Part Differential Hematology Analyzer (Flow Cytometry & Impedance)',
    notesDefault: 'مكونات الدم ضمن المعدلات الطبيعية المتوافقة مع العمر والجنس.',
    notesDefaultEn: 'Hematological parameters are within expected biological reference intervals for age and gender.',
    fields: [
      {
        id: 'hb',
        nameAr: 'الهيموجلوبين (Hemoglobin - Hb)',
        nameEn: 'Hemoglobin (Hb)',
        unit: 'g/dL',
        defaultValue: '14.2',
        normalRange: 'M: 13.0 - 17.5 / F: 12.0 - 15.5',
        normalMin: 12.0,
        normalMax: 17.5,
      },
      {
        id: 'rbc',
        nameAr: 'كرات الدم الحمراء (RBC Count)',
        nameEn: 'Red Blood Cells (RBC Count)',
        unit: '×10⁶/µL',
        defaultValue: '4.8',
        normalRange: 'M: 4.5 - 5.9 / F: 4.0 - 5.2',
        normalMin: 4.0,
        normalMax: 5.9,
      },
      {
        id: 'hct',
        nameAr: 'حجم الخلايا المتكدسة (Hematocrit - PCV)',
        nameEn: 'Hematocrit (HCT / PCV)',
        unit: '%',
        defaultValue: '42',
        normalRange: 'M: 40 - 52 % / F: 36 - 48 %',
        normalMin: 36,
        normalMax: 52,
      },
      {
        id: 'mcv',
        nameAr: 'متوسط حجم الكرية (MCV)',
        nameEn: 'Mean Corpuscular Volume (MCV)',
        unit: 'fL',
        defaultValue: '87',
        normalRange: '80 - 100 fL',
        normalMin: 80,
        normalMax: 100,
      },
      {
        id: 'mch',
        nameAr: 'متوسط هيموجلوبين الكرية (MCH)',
        nameEn: 'Mean Corpuscular Hemoglobin (MCH)',
        unit: 'pg',
        defaultValue: '29.5',
        normalRange: '27 - 33 pg',
        normalMin: 27,
        normalMax: 33,
      },
      {
        id: 'mchc',
        nameAr: 'تركيز هيموجلوبين الكريات (MCHC)',
        nameEn: 'M.C.H.C',
        unit: 'g/dL',
        defaultValue: '33.5',
        normalRange: '32 - 36 g/dL',
        normalMin: 32,
        normalMax: 36,
      },
      {
        id: 'wbc',
        nameAr: 'كرات الدم البيضاء الكلية (Total WBCs)',
        nameEn: 'Total White Blood Cells (WBC)',
        unit: '×10³/µL',
        defaultValue: '6.8',
        normalRange: '4.0 - 11.0 ×10³/µL',
        normalMin: 4.0,
        normalMax: 11.0,
      },
      {
        id: 'neutrophils',
        nameAr: 'الخلايا المتعادلة (Neutrophils %)',
        nameEn: 'Neutrophils %',
        unit: '%',
        defaultValue: '58',
        normalRange: '40 - 70 %',
        normalMin: 40,
        normalMax: 70,
      },
      {
        id: 'lymphocytes',
        nameAr: 'الخلايا الليمفاوية (Lymphocytes %)',
        nameEn: 'Lymphocytes %',
        unit: '%',
        defaultValue: '32',
        normalRange: '20 - 45 %',
        normalMin: 20,
        normalMax: 45,
      },
      {
        id: 'plt',
        nameAr: 'الصفائح الدموية (Platelet Count)',
        nameEn: 'Platelets Count (PLT)',
        unit: '×10³/µL',
        defaultValue: '245',
        normalRange: '150 - 450 ×10³/µL',
        normalMin: 150,
        normalMax: 450,
      },
    ],
  },
  {
    id: 'rft',
    titleAr: 'وظائف الكلى الكاملة',
    titleEn: 'Kidney Function Tests (RFT)',
    category: 'الكلى والمسالك',
    categoryEn: 'Renal Function & Nephrology',
    methodology: 'Enzymatic / Jaffe Kinetic & Urease-GLDH',
    notesDefault: 'معدل الترشيح الكبيبي المقدر (eGFR) طبيعي (> 90 mL/min/1.73m²).',
    notesDefaultEn: 'Estimated glomerular filtration rate (eGFR) is normal. Renal clearance parameters are preserved.',
    fields: [
      {
        id: 'creatinine',
        nameAr: 'الكرياتينين في المصل (Serum Creatinine)',
        nameEn: 'Serum Creatinine',
        unit: 'mg/dL',
        defaultValue: '0.9',
        normalRange: '0.6 - 1.2 mg/dL (M: 0.7-1.3 / F: 0.5-1.1)',
        normalMin: 0.6,
        normalMax: 1.2,
      },
      {
        id: 'blood_urea',
        nameAr: 'اليوريا في الدم (Blood Urea)',
        nameEn: 'Blood Urea',
        unit: 'mg/dL',
        defaultValue: '28',
        normalRange: '15 - 45 mg/dL',
        normalMin: 15,
        normalMax: 45,
      },
      {
        id: 'bun',
        nameAr: 'نيتروجين اليوريا (BUN)',
        nameEn: 'Blood Urea Nitrogen (BUN)',
        unit: 'mg/dL',
        defaultValue: '13',
        normalRange: '7 - 20 mg/dL',
        normalMin: 7,
        normalMax: 20,
      },
      {
        id: 'uric_acid',
        nameAr: 'حمض اليوريك (Serum Uric Acid)',
        nameEn: 'Serum Uric Acid',
        unit: 'mg/dL',
        defaultValue: '4.8',
        normalRange: 'M: 3.5 - 7.2 / F: 2.6 - 6.0 mg/dL',
        normalMin: 3.5,
        normalMax: 7.2,
      },
      {
        id: 'egfr',
        nameAr: 'معدل الترشيح الكبيبي (eGFR)',
        nameEn: 'Estimated GFR (eGFR)',
        unit: 'mL/min/1.73m²',
        defaultValue: '98',
        normalRange: '> 90 mL/min/1.73m²',
        normalMin: 90,
        normalMax: 140,
      },
    ],
  },
  {
    id: 'lft',
    titleAr: 'وظائف الكبد الكاملة',
    titleEn: 'Liver Function Tests (LFT)',
    category: 'الجهاز الهضمي والكبد',
    categoryEn: 'Hepatic Function & Gastroenterology',
    methodology: 'IFCC UV with Pyridoxal Phosphate & Diazo Photometric',
    notesDefault: 'أنزيمات الكبد والبروتينات في الحدود الطبيعية.',
    notesDefaultEn: 'Hepatic transaminases, biliary excretory markers, and synthetic albumin within normal limits.',
    fields: [
      {
        id: 'sgpt',
        nameAr: 'إنزيم الكبد ALT (SGPT)',
        nameEn: 'Alanine Aminotransferase (ALT / SGPT)',
        unit: 'U/L',
        defaultValue: '26',
        normalRange: 'Up to 45 U/L (M: <50 / F: <35)',
        normalMin: 0,
        normalMax: 45,
      },
      {
        id: 'sgot',
        nameAr: 'إنزيم الكبد AST (SGOT)',
        nameEn: 'Aspartate Aminotransferase (AST / SGOT)',
        unit: 'U/L',
        defaultValue: '24',
        normalRange: 'Up to 40 U/L (M: <45 / F: <35)',
        normalMin: 0,
        normalMax: 40,
      },
      {
        id: 'total_bilirubin',
        nameAr: 'الصفراء الكلية (Total Bilirubin)',
        nameEn: 'Total Bilirubin',
        unit: 'mg/dL',
        defaultValue: '0.7',
        normalRange: '0.2 - 1.2 mg/dL',
        normalMin: 0.2,
        normalMax: 1.2,
      },
      {
        id: 'direct_bilirubin',
        nameAr: 'الصفراء المباشرة (Direct Bilirubin)',
        nameEn: 'Direct Bilirubin',
        unit: 'mg/dL',
        defaultValue: '0.15',
        normalRange: '0.0 - 0.3 mg/dL',
        normalMin: 0.0,
        normalMax: 0.3,
      },
      {
        id: 'albumin',
        nameAr: 'الزلال في الدم (Serum Albumin)',
        nameEn: 'Serum Albumin',
        unit: 'g/dL',
        defaultValue: '4.2',
        normalRange: '3.5 - 5.2 g/dL',
        normalMin: 3.5,
        normalMax: 5.2,
      },
      {
        id: 'total_protein',
        nameAr: 'البروتين الكلي (Total Protein)',
        nameEn: 'Total Protein',
        unit: 'g/dL',
        defaultValue: '7.1',
        normalRange: '6.4 - 8.3 g/dL',
        normalMin: 6.4,
        normalMax: 8.3,
      },
      {
        id: 'alp',
        nameAr: 'الفوسفاتاز القلوي (ALP)',
        nameEn: 'Alkaline Phosphatase (ALP)',
        unit: 'U/L',
        defaultValue: '78',
        normalRange: '44 - 147 U/L',
        normalMin: 44,
        normalMax: 147,
      },
    ],
  },
  {
    id: 'lipid_profile',
    titleAr: 'دهون الدم الشاملة',
    titleEn: 'Lipid Profile Panel',
    category: 'القلب والأوعية الدموية',
    categoryEn: 'Lipidology & Cardiovascular',
    methodology: 'Enzymatic Colorimetric (CHOD-PAP / GPO-PAP)',
    notesDefault: 'سُحبت العينة بعد صيام 10-12 ساعة.',
    notesDefaultEn: 'Specimen collected following 10-12 hours overnight fasting. Calculated LDL by Friedewald equation.',
    fields: [
      {
        id: 'cholesterol',
        nameAr: 'الكوليسترول الكلي (Total Cholesterol)',
        nameEn: 'Total Cholesterol',
        unit: 'mg/dL',
        defaultValue: '175',
        normalRange: '< 200 mg/dL (Desirable)',
        normalMin: 0,
        normalMax: 200,
      },
      {
        id: 'triglycerides',
        nameAr: 'الدهون الثلاثية (Triglycerides)',
        nameEn: 'Serum Triglycerides',
        unit: 'mg/dL',
        defaultValue: '130',
        normalRange: '< 150 mg/dL (Normal)',
        normalMin: 0,
        normalMax: 150,
      },
      {
        id: 'hdl',
        nameAr: 'الكوليسترول النافع (HDL - High Density)',
        nameEn: 'HDL Cholesterol',
        unit: 'mg/dL',
        defaultValue: '52',
        normalRange: 'M: > 40 / F: > 50 mg/dL',
        normalMin: 40,
        normalMax: 80,
      },
      {
        id: 'ldl',
        nameAr: 'الكوليسترول الضار (LDL - Low Density)',
        nameEn: 'LDL Cholesterol',
        unit: 'mg/dL',
        defaultValue: '98',
        normalRange: '< 100 mg/dL (Optimal)',
        normalMin: 0,
        normalMax: 100,
      },
      {
        id: 'risk_ratio',
        nameAr: 'مؤشر خطورة القلب (Total / HDL Ratio)',
        nameEn: 'Coronary Risk Ratio (TC / HDL)',
        unit: 'Ratio',
        defaultValue: '3.3',
        normalRange: '< 4.5 (Low Risk)',
        normalMin: 0,
        normalMax: 4.5,
      },
    ],
  },
  {
    id: 'thyroid',
    titleAr: 'هرمونات الغدة الدرقية',
    titleEn: 'Thyroid Hormones Profile',
    category: 'الغدد الصماء والهرمونات',
    categoryEn: 'Endocrinology',
    methodology: 'Chemiluminescence Immunoassay (CLIA)',
    notesDefault: 'مستويات هرمونات الغدة الدرقية طبيعية (Euthyroid state).',
    notesDefaultEn: 'Euthyroid biological state. No primary thyroid hyper- or hypo-function indicated.',
    fields: [
      {
        id: 'tsh',
        nameAr: 'الهرمون المنبه للدرقية (TSH)',
        nameEn: 'Thyroid Stimulating Hormone (TSH)',
        unit: 'µIU/mL',
        defaultValue: '2.1',
        normalRange: '0.4 - 4.2 µIU/mL',
        normalMin: 0.4,
        normalMax: 4.2,
      },
      {
        id: 'ft3',
        nameAr: 'الثيروكسين الحر (Free T3)',
        nameEn: 'Free Triiodothyronine (FT3)',
        unit: 'pg/mL',
        defaultValue: '3.1',
        normalRange: '2.0 - 4.4 pg/mL',
        normalMin: 2.0,
        normalMax: 4.4,
      },
      {
        id: 'ft4',
        nameAr: 'الثيروكسين الحر (Free T4)',
        nameEn: 'Free Thyroxine (FT4)',
        unit: 'ng/dL',
        defaultValue: '1.25',
        normalRange: '0.8 - 1.8 ng/dL',
        normalMin: 0.8,
        normalMax: 1.8,
      },
    ],
  },
  {
    id: 'vitamins',
    titleAr: 'فيتامين د وفيتامين ب12 والحديد',
    titleEn: 'Vitamins & Iron Profile (D3, B12, Ferritin)',
    category: 'الفيتامينات والمعادن',
    categoryEn: 'Vitamins & Trace Elements',
    methodology: 'ECLIA / CLIA Chemiluminescence',
    notesDefault: 'معدلات الفيتامينات الأساسية الحيوية.',
    notesDefaultEn: 'Serum concentrations verified by standardized electrochemiluminescence immunoassay.',
    fields: [
      {
        id: 'vit_d',
        nameAr: 'فيتامين د الكلي (25-OH Vitamin D)',
        nameEn: '25-Hydroxy Vitamin D (25-OH Vit D)',
        unit: 'ng/mL',
        defaultValue: '38',
        normalRange: '30 - 100 ng/mL (Sufficient)',
        normalMin: 30,
        normalMax: 100,
      },
      {
        id: 'vit_b12',
        nameAr: 'فيتامين ب12 (Vitamin B12)',
        nameEn: 'Cyanocobalamin (Vit B12)',
        unit: 'pg/mL',
        defaultValue: '450',
        normalRange: '200 - 900 pg/mL',
        normalMin: 200,
        normalMax: 900,
      },
      {
        id: 'ferritin',
        nameAr: 'مخزون الحديد (Serum Ferritin)',
        nameEn: 'Serum Ferritin',
        unit: 'ng/mL',
        defaultValue: '85',
        normalRange: 'M: 30 - 300 / F: 15 - 200 ng/mL',
        normalMin: 15,
        normalMax: 300,
      },
    ],
  },
  {
    id: 'custom',
    titleAr: 'قالب فحص مخصص',
    titleEn: 'Custom Laboratory Investigation',
    category: 'فحوصات مخصصة',
    categoryEn: 'Custom Clinical Investigation',
    methodology: 'Standard Clinical Laboratory Protocol',
    notesDefault: 'تم إجراء الفحص والتحقق من النتيجة مخبرياً.',
    notesDefaultEn: 'Investigation performed and authenticated in accordance with standard diagnostic protocols.',
    fields: [
      {
        id: 'param_1',
        nameAr: 'اسم التحليل / الباراميتر',
        nameEn: 'Investigation Name',
        unit: 'mg/dL',
        defaultValue: '',
        normalRange: 'Biological Reference Range',
      },
    ],
  },
];
